# Generated by Django 5.1.3 on 2024-11-20 00:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('company_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('industry', models.TextField()),
                ('location', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('unique_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('email', models.TextField()),
                ('college', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('role_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.TextField()),
                ('job_type', models.TextField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rate_my_interviewer.company')),
            ],
        ),
        migrations.CreateModel(
            name='InterviewExperience',
            fields=[
                ('experience_id', models.AutoField(primary_key=True, serialize=False)),
                ('experience_text', models.TextField()),
                ('date_shared', models.DateField(auto_now_add=True)),
                ('rating', models.IntegerField()),
                ('difficulty', models.IntegerField()),
                ('like', models.IntegerField(default=0)),
                ('dislike', models.IntegerField(default=0)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rate_my_interviewer.company')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rate_my_interviewer.role')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rate_my_interviewer.user')),
            ],
        ),
    ]
