# Generated by Django 5.1.3 on 2024-11-20 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rate_my_interviewer', '0002_user_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interviewexperience',
            name='dislike',
        ),
        migrations.RemoveField(
            model_name='interviewexperience',
            name='like',
        ),
        migrations.AddField(
            model_name='interviewexperience',
            name='job_type',
            field=models.TextField(default=''),
        ),
    ]
