# Generated by Django 5.1.3 on 2024-11-20 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rate_my_interviewer', '0003_remove_interviewexperience_dislike_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interviewexperience',
            name='role',
            field=models.TextField(),
        ),
    ]
