# Generated by Django 5.1.3 on 2024-11-20 22:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rate_my_interviewer', '0004_alter_interviewexperience_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interviewexperience',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rate_my_interviewer.user'),
        ),
    ]
