# Generated by Django 5.1.3 on 2024-11-20 22:32

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rate_my_interviewer', '0005_alter_interviewexperience_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='RMIProfile',
        ),
    ]
