# Generated by Django 5.1.1 on 2024-12-01 22:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rate_my_interviewer', '0006_rename_user_rmiprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewexperience',
            name='dislikes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='interviewexperience',
            name='likes',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('text', models.TextField()),
                ('date_shared', models.DateField(auto_now_add=True)),
                ('experience', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rate_my_interviewer.interviewexperience')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rate_my_interviewer.rmiprofile')),
            ],
        ),
    ]
