# Generated by Django 5.1.3 on 2024-12-06 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rate_my_interviewer', '0009_remove_likes_experience_remove_likes_user_question_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewexperience',
            name='offer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='interviewexperience',
            name='paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='interviewexperience',
            name='question',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='interviewexperience',
            name='type',
            field=models.CharField(choices=[('Behavioral', 'Behavioral'), ('Technical', 'Technical'), ('Case Study', 'Case Study')], default='Behavioral', max_length=50),
        ),
        migrations.AddField(
            model_name='rmiprofile',
            name='credits',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
