# Generated by Django 5.1.3 on 2024-12-06 02:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rate_my_interviewer', '0010_interviewexperience_offer_interviewexperience_paid_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Unlock',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('experience', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rate_my_interviewer.interviewexperience')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rate_my_interviewer.rmiprofile')),
            ],
        ),
    ]
