# Generated by Django 5.1.3 on 2024-12-06 03:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rate_my_interviewer', '0012_checkin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='checkin',
            old_name='Date',
            new_name='date',
        ),
    ]
