# Generated by Django 5.1.3 on 2024-12-07 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rate_my_interviewer', '0013_rename_date_checkin_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='interviewexperience',
            old_name='paid',
            new_name='creduts_required',
        ),
        migrations.AddField(
            model_name='interviewexperience',
            name='credits_amount',
            field=models.IntegerField(default=0),
        ),
    ]
