# Generated by Django 5.1.3 on 2024-12-07 02:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rate_my_interviewer', '0014_rename_paid_interviewexperience_creduts_required_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='interviewexperience',
            old_name='creduts_required',
            new_name='credits_required',
        ),
    ]
